# Leukocyte identification

In [1]:
from keras.applications.resnet50 import ResNet50
from keras.applications.resnet50 import preprocess_input, decode_predictions
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg19 import VGG19
from keras.applications.vgg19 import preprocess_input
from keras.applications.inception_v3 import InceptionV3
from keras.applications.densenet import DenseNet121
from keras.applications.densenet import DenseNet169
from keras.applications.densenet import DenseNet201
from keras.applications.nasnet import NASNetLarge
from keras.applications.nasnet import NASNetMobile
from keras.applications.inception_resnet_v2 import InceptionResNetV2
from keras.applications.xception import Xception
from keras.applications.mobilenet import MobileNet

#from keras.preprocessing import image
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Input, Dropout
from keras.utils import to_categorical
import numpy as np
from keras.models import Model
import pandas as pd
import keras as K
import os
import cv2
import scipy
#import keras.backend as K
from sklearn.preprocessing import LabelEncoder
from keras.optimizers import SGD, Adam, Adagrad, RMSprop
from keras.preprocessing.image import ImageDataGenerator
from keras.utils import np_utils

##lIMPAR
# from keras.models import Sequential
# from keras.layers import Dense, Dropout, Activation, Flatten
# from keras.layers import Conv2D, MaxPooling2D, BatchNormalization, Lambda
# from keras.layers import Dense


# from keras.wrappers.scikit_learn import KerasClassifier
# from keras.utils import to_categorical

# from sklearn.model_selection import train_test_split
# from sklearn.metrics import log_loss
# from custom_layers.scale_layer import Scale
# from load_cifar10 import load_cifar10_data

import keras.backend as K
import scipy
%matplotlib inline
import matplotlib.pyplot as plt

C:\Users\Ana Brites\AppData\Local\conda\conda\envs\ztdl\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
epochs = 5
batch_size = 16
# num_classes=4 # REVIEW for using models pre trained with 'imagenet' where 'classes=1000'

## Models

In [3]:
models= [] ## use to plot all the results...
models_names = []


# ##ResNet50 (224, 224, 3)
resnet50 = ResNet50(weights= 'imagenet', classes=4, include_top=False)
models.append(resnet50)
models_names.append('ResNet50')

# # #VGG16 (224, 224, 3)
# vgg16 = VGG16()
# # #keras.applications.vgg16.VGG16(include_top=True, weights='imagenetacti', input_tensor=None, input_shape=None, pooling=None, classes=1000)
# models.append(vgg16)


# # #VGG19 (224, 224, 3) 
# vgg19= VGG19(weights= None, classes = 4)
# # or
# # base_model = VGG19(classes=4) ### NOT WORKING
# # vgg19= Model(inputs=base_model.input, outputs=base_model.get_layer('block4_pool').output)
# models.append(vgg19)


# ###InceptionV3 (299, 299, 3)
# input_tensor = Input(shape=(224, 224, 3))  # this assumes K.image_data_format() == 'channels_last'
# inceptionv3 = InceptionV3(input_tensor=input_tensor, weights= None, include_top=True, classes = 4)
# models.append(inceptionv3)


# # #InceptionResNetV2 (299, 299, 3)
# inceptionresnetv2= InceptionResNetV2(weights= None, classes = 4)
# # model = keras.applications.inception_resnet_v2.InceptionResNetV2(weights= None)
# models.append(inceptionresnetv2)


# ###Xception (299, 299, 3)
# xception = Xception()
# #keras.applications.xception.Xception(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)
# models.append(xception)


# ###MobileNet (224, 224, 3) # ???????????????????
# # keras.applications.mobilenet.MobileNet(input_shape=None, alpha=1.0, depth_multiplier=1, dropout=1e-3, include_top=True, weights='imagenet', input_tensor=None, pooling=None, classes=1000)
# mobilenet = load_model('mobilenet.h5', custom_objects={
#                         'relu6': mobilenet.relu6,
#                         'DepthwiseConv2D': mobilenet.DepthwiseConv2D})
# models.append(mobilenet)


# ###DenseNet (224, 224, 3)
# # model= DenseNet121(weights=None)
# densenet121= DenseNet121()
# ## keras.applications.densenet.DenseNet121(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)
# densenet169= DenseNet169()
# ## keras.applications.densenet.DenseNet169(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)
# densenet201= DenseNet201()
# ## keras.applications.densenet.DenseNet201(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)
# models.append(densenet121)
# models.append(densenet169)
# models.append(densenet201)


###NASNet (224, 224, 3)mobile & (331, 331, 3)Large
#nasnetlarge= NASNetLarge() #### NOT WORKING
# keras.applications.nasnet.NASNetLarge(input_shape=None, include_top=True, weights='imagenet', input_tensor=None, pooling=None, classes=1000)
#nasnetmobile = NASNetMobile()
# keras.applications.nasnet.NASNetMobile(input_shape=None, include_top=True, weights='imagenet', input_tensor=None, pooling=None, classes=1000)
#models.append(nasnetlarge)
#models.append(nasnetmobile)



In [4]:
print(len(models))

1


In [5]:
# def get_data(folder):
#     """
#     Load the data and labels from the given folder.
#     """
#     X = []
#     y = []

#     for wbc_type in os.listdir(folder):
#         if not wbc_type.startswith('.'):
#             if wbc_type in 'NEUTROPHIL':
#                 label = 'NEUTROPHIL'
#             if wbc_type in 'EOSINOPHIL':
#                 label = 'EOSINOPHIL'
#             if wbc_type in 'MONOCYTE':
#                 label = 'MONOCYTE'
#             if wbc_type in 'LYMPHOCYTE':   
#                 label = 'LYMPHOCYTE'
#             for image_filename in os.listdir(folder + wbc_type):
#                 img_file = cv2.imread(folder + wbc_type + '/' + image_filename)
#                 if img_file is not None:
#                     # Downsample the image
#                     img_file = scipy.misc.imresize(arr=img_file, size=(224, 224, 3)) 
#                         # size=(224, 224, 3) for ResNet50, VGG16, VGG19, NASNetmobile, MobileNet
#                         # size=(299, 299, 3) for InceptionV3,
#                         # size=(331, 331, 3) for NASNetLarge
#                     img_arr = np.asarray(img_file)
#                     X.append(img_arr)
#                     y.append(label)
#     X = np.asarray(X)
#     y = np.asarray(y)
#     return X,y

In [6]:
''' jupyter nbk or floyd hub? 
        mode = ... '''

mode = 'jupyter'
#mode = 'floyd'

if mode == 'floyd':
    BASE_DIR = '/img/'
        
elif mode == 'jupyter':
    BASE_DIR = 'C:/Users/Ana Brites/dataleuko/' 

In [7]:
# def xy_test_train(mode):
#     X_train, y_train = get_data(BASE_DIR + 'images/TRAIN/') 
#     X_test, y_test = get_data(BASE_DIR + 'images/TEST_SIMPLE2/')
#     return X_train, y_train, X_test, y_test

In [8]:
# X_train, y_train, X_test, y_test= xy_test_train(mode)

In [9]:
model = models[0]

### Generate and save data

In [ ]:
# From the original 358 images on training set where generated 10000

In [ ]:
# this is the augmentation configuration we will use for training
datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

In [ ]:
generator = datagen.flow_from_directory(
        BASE_DIR + 'images/TRAIN',
        target_size=(224, 224),
        batch_size=batch_size,
        class_mode=None,  # this means our generator will only yield batches of data, no labels
        shuffle=False)  # our data will be in order, so all first 1000 images will be cats, then 1000 dogs
# the predict_generator method returns the output of a model, given
# a generator that yields batches of numpy data

In [ ]:
bottleneck_features_train = model.predict_generator(generator, 10000, verbose=1) 
# Saved arrays created with 9000 (number available in floydhub)

In [ ]:
len(bottleneck_features_train)

In [ ]:
# save the output as a Numpy array
np.save(open('bottleneck_features_train.npy', 'wb'), bottleneck_features_train) ### 'wb' or 'w'

In [ ]:
generator = datagen.flow_from_directory(
        BASE_DIR + 'images/TEST_SIMPLE2',
        target_size=(224, 224),
        batch_size=batch_size,
        class_mode=None,
        shuffle=False)

In [ ]:
bottleneck_features_validation = model.predict_generator(generator, 1600) 
# Saved arrays created with 600

In [ ]:
np.save(open('bottleneck_features_validation.npy', 'wb'), bottleneck_features_validation)

### Load data

In [10]:
train_data = np.load(open('bottleneck_features_train.npy','rb'))
validation_data = np.load(open('bottleneck_features_validation.npy','rb'))
# the features were saved in order...

In [11]:
# # Check size
# print(train_data)
# print(validation_data)
print(train_data.shape)
print(validation_data.shape)

(144000, 1, 1, 2048)
(9600, 1, 1, 2048)


In [ ]:
print(train_data)

In [93]:
train_labels = np.vstack(([[0]]* (36000), [[1]]* (36000), [[2]] * (36000),[[3]] * (36000))) #??
validation_labels = np.vstack(([[0]]* (2400), [[1]] * (2400), [[2]] * (2400), [[3]] * (2400)))

In [61]:
# train_labels = np.transpose(np.column_stack(([0] * 36000, [1] * 36000, [2] * 36000, [3] * 36000))) #??
# validation_labels = np.transpose(np.column_stack(([0] * 2400, [1] * 2400 , [2] * 2400 , [3] * 2400)))

In [70]:
train_labels

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       ...,
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [44]:
#train_labels = np.transpose(train_labels)

In [65]:
print(train_labels2)
#print(validation_labels.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [71]:
len(train_labels)

144000

In [75]:
print(len(train_labels))
#print(validation_labels)

144000


In [52]:
#Fazer shuffle???

In [53]:
print(len(train_data))
print(len(train_labels))
print(len(validation_data))
print(len(validation_labels))

144000
4
9600
4


In [78]:
print(validation_labels.shape)
print(train_labels.shape)

(9600, 4)
(144000, 4)


### Encoder1

In [90]:
def onehotencode(Y):
        # encode class values as integers
        encoder = LabelEncoder()
        encoder.fit(Y)
        encoded_Y = encoder.transform(Y)
        # convert integers to dummy variables (i.e. one hot encoded)
        dummy_y = np_utils.to_categorical(encoded_Y)
        return dummy_y

In [94]:
train_labels = onehotencode(train_labels)
validation_labels = onehotencode(validation_labels)

C:\Users\Ana Brites\AppData\Local\conda\conda\envs\ztdl\lib\site-packages\sklearn\preprocessing\label.py:112: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ana Brites\AppData\Local\conda\conda\envs\ztdl\lib\site-packages\sklearn\preprocessing\label.py:147: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [95]:
print(validation_labels)
print(train_labels)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


### Encoder2

In [22]:
validation_labels = to_categorical(validation_labels)
train_labels = to_categorical(train_labels)

In [23]:
print(validation_labels)
print(train_labels)

[[[0. 1.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 ...

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [0. 1.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [0. 1.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [0. 1.]]]
[[[0. 1.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 ...

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [0. 1.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [0. 1.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [0. 1.]]]


### Shuffle

In [97]:
def shuffle_in_unison(a, b):
    assert len(a) == len(b)
    shuffled_a = np.empty(a.shape, dtype=a.dtype)
    shuffled_b = np.empty(b.shape, dtype=b.dtype)
    permutation = np.random.permutation(len(a))
    for old_index, new_index in enumerate(permutation):
        shuffled_a[new_index] = a[old_index]
        shuffled_b[new_index] = b[old_index]
    return shuffled_a, shuffled_b

In [98]:
X_train, y_train  = shuffle_in_unison(train_data, train_labels)
X_val, y_val  = shuffle_in_unison(validation_data, validation_labels)

In [99]:
## Confirm shape
print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(y_val.shape)

(144000, 1, 1, 2048)
(144000, 4)
(9600, 1, 1, 2048)
(9600, 4)


In [27]:
y_train

array([[[1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.]],

       [[0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       ...,

       [[0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]]], dtype=float32)

In [28]:
y_val

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]],

       [[1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]],

       ...,

       [[0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]]], dtype=float32)

### Model top

In [104]:
model = Sequential()
model.add(Flatten(input_shape=X_train.shape[1:]))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(4, activation='softmax'))
#Alterar parâmetros...
#Adicionar mais uma dense

In [105]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [106]:
print(X_train.shape)
print(X_val.shape)
print(y_train.shape)
print(y_val.shape)

(144000, 1, 1, 2048)
(9600, 1, 1, 2048)
(144000, 4)
(9600, 4)


In [107]:
model.fit(X_train, y_train,
          epochs=50,
          batch_size=batch_size,
          validation_data=(X_val, y_val))

Train on 144000 samples, validate on 9600 samples
Epoch 1/50
144000/144000 [==============================] - 160s 1ms/step - loss: 1.3874 - acc: 0.2497 - val_loss: 1.3864 - val_acc: 0.2500
Epoch 2/50
144000/144000 [==============================] - 154s 1ms/step - loss: 1.3864 - acc: 0.2513 - val_loss: 1.3864 - val_acc: 0.2500
Epoch 3/50
142720/144000 [============================>.] - ETA: 1s - loss: 1.3864 - acc: 0.2479

KeyboardInterrupt: 

In [ ]:
model.save_weights('bottleneck_fc_model.h5')

In [ ]:
#Encode y_train and y_test

def encoder(y_train, y_test):
    encoder = LabelEncoder()
    encoder.fit(y_train)
    y_train = encoder.transform(y_train)
    y_test = encoder.transform(y_test)
    
    return y_train, y_test

In [ ]:
#Encoding??
y_train, y_test = encoder(y_train, y_test)

In [ ]:
sizes =[X_train.shape, y_train.shape, X_test.shape, y_test.shape]
print(sizes)

In [ ]:
print(y_train)
print(y_test)

## Shuffle

In [ ]:
def shuffle_in_unison(a, b):
    assert len(a) == len(b)
    shuffled_a = np.empty(a.shape, dtype=a.dtype)
    shuffled_b = np.empty(b.shape, dtype=b.dtype)
    permutation = np.random.permutation(len(a))
    for old_index, new_index in enumerate(permutation):
        shuffled_a[new_index] = a[old_index]
        shuffled_b[new_index] = b[old_index]
    return shuffled_a, shuffled_b

In [ ]:
X_train, y_train = shuffle_in_unison(X_train, y_train)
X_test, y_test = shuffle_in_unison(X_test, y_test)

In [ ]:
## Confirm shape
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

In [ ]:
## Check datasets
print(y_train)
print(y_test)

In [ ]:
print(encoder(y_train, y_test))

In [ ]:
#Create TRAIN and VALIDATION sets?????
#X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [ ]:
model=models[0]
#K.clear_session()

adm=Adam(lr=0.0001, beta_1=0.95, beta_2=0.9995)

#for model in models:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=adm,
              metrics=['accuracy'])
              #verbose= True)

# fits the model on batches
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=epochs,
    shuffle=True,
    batch_size=batch_size)

#model.save_weights('model_weights.h5')

In [ ]:
## load json and create model

json_file = open("model-{}.json".format(models_names[0]), 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model-{}.json".format(models_names[0]))
print("Loaded model from disk")
 
    
# evaluate loaded model on test data
loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
score = loaded_model.evaluate(X_test, Y_test, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))
# print('Test loss:', score[0])
# print('Test accuracy:', score[1])


In [ ]:
# Save model and weights 2

# serialize model to JSON
from keras.models import model_from_json
#from keras.models import load_models

model_json = model.to_json()
with open("model-{}.json".format(models_names[0]), "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model-{}.json.h5".format(models_names[0]))
print("Saved model to disk")
 
# later...
 
# # load json and create model
# json_file = open('model.json', 'r')
# loaded_model_json = json_file.read()
# json_file.close()
# loaded_model = model_from_json(loaded_model_json)
# # load weights into new model
# loaded_model.load_weights("model.h5")
# print("Loaded model from disk")
 
# # evaluate loaded model on test data
# loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
# score = loaded_model.evaluate(X, Y, verbose=0)
# print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

In [ ]:
# list all data in history
print(history.history.keys())

# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
#Model evaluate

score = model.evaluate(X_test, y_test_enc, verbose=0)
print('Test Loss', score[0])
print('Test accuracy:', score[1])

test_image = X_test[0:1]
print(test_image.shape)
print(model.predict(test_image))
print(model.predict(test_image))
print(y_test[0:1])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools

#predict(self, x, batch_size=None, verbose=0, steps=None)

y_pred = model.predict(X_test)
print(y_pred)
y_pred = np.argmax(y_pred, axis=1)
print(y_pred)
  

#y_pred = model.predict(X_test) #model has no predict_classes
#print(y_pred)

#p=model.predict_proba(X_test) #model has no predict_proba

target_names = ['class 0(EOSINOPHIL)', 'class 1(LYPHOCYTE)', 'class 2(MONOCYTE)', 'class 3(NEUTROPHIL)'] ##REVIEW
print(classification_report(np.argmax(y_test,axis=1), y_pred,target_names=target_names))
print(confusion_matrix(np.argmax(y_test,axis=1), y_pred))

In [ ]:
# Visualizing intermediate layers outputs

#test_image =

def get_featuremaps(model, layer_idx, X_batch):
    get_activations = K.function([model.layers[0].input, K.learning_phase()], [model.layers[layer_idx].output,])
    activations = get_activations([X_batch,0])
    
layer_num=0
filter_num=0
    
activations = get_featuremaps(model, int(layer_num), test_image)
#Test with one image only
    
print(np.shape(activations))
feature_maps = activations[0][0]
print(np.shape(feature_maps))

print(feature_maps.shape)

fig=plt.figure(figsize=(16,16))
plt.imshow(feature_maps[:,:,filter_num],cmap='gray')
plt.savefig("featuremaps-layer-{}".format(layer_num)+"-filternum-{}".format(filter_num)+'.jpg')


In [ ]:
# Visualizing intermediate layers outputs, all filters
fig=plt.figure(figsize=(16,16))
plt.imshow(feature_maps[:,:,filter_num],cmap='gray')
plt.savefig("featuremaps-layer-{}".format(layer_num)+"-filternum-{}".format(filter_num)+'.jpg')

num_of_featuremaps=feature_maps.shape[2]
fig=plt.figure(figsize=(16,16))
plt.title("featuremaps-layer-{}".format(layer_num))
subplot_num=int(np.ceil(np.sqrt(num_of_featuremaps)))
for i in range(int(num_of_featuremaps)):
    ax= fig.add_subplot(subplot_num, subplot_num, i+1)
    ax.imshow(feature_maps[:,:,i], cmap='gray')
    plt.xticks([])
    plt.yticks([])
    plt.tight_layou()
plt.show()
fig.savefig("featuremaps-layer-{}".format(layer_num)+'.jpg')


In [ ]:
# def change_shape(y_train):
#     y_train = y_train.reshape(len(y_train),1)
#     return y_train

## Save models and plot

In [ ]:
# Save model and weights 

# serialize model to JSON
from keras.models import model_from_json
#from keras.models import load_models

model_json = model.to_json()
with open("model-{}.json".format(models_names[0]), "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model-{}.json.h5".format(models_names[0]))
print("Saved model to disk")
 
# later...
 
# # load json and create model
# json_file = open('model.json', 'r')
# loaded_model_json = json_file.read()
# json_file.close()
# loaded_model = model_from_json(loaded_model_json)
# # load weights into new model
# loaded_model.load_weights("model.h5")
# print("Loaded model from disk")
 
# # evaluate loaded model on test data
# loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
# score = loaded_model.evaluate(X, Y, verbose=0)
# print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

# list all data in history
print(history.history.keys())

# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

#Model evaluate

score = model.evaluate(X_test, y_test_enc, verbose=0)
print('Test Loss', score[0])
print('Test accuracy:', score[1])

test_image = X_test[0:1]
print(test_image.shape)
print(model.predict(test_image))
print(model.predict(test_image))
print(y_test[0:1])

from sklearn.metrics import classification_report, confusion_matrix
import itertools

#predict(self, x, batch_size=None, verbose=0, steps=None)

y_pred = model.predict(X_test)
print(y_pred)
y_pred = np.argmax(y_pred, axis=1)
print(y_pred)
  

#y_pred = model.predict(X_test) #model has no predict_classes
#print(y_pred)

#p=model.predict_proba(X_test) #model has no predict_proba

target_names = ['class 0(EOSINOPHIL)', 'class 1(LYPHOCYTE)', 'class 2(MONOCYTE)', 'class 3(NEUTROPHIL)'] ##REVIEW
print(classification_report(np.argmax(y_test,axis=1), y_pred,target_names=target_names))
print(confusion_matrix(np.argmax(y_test,axis=1), y_pred))

# Visualizing intermediate layers outputs

#test_image =

def get_featuremaps(model, layer_idx, X_batch):
    get_activations = K.function([model.layers[0].input, K.learning_phase()], [model.layers[layer_idx].output,])
    activations = get_activations([X_batch,0])
    
layer_num=0
filter_num=0
    
activations = get_featuremaps(model, int(layer_num), test_image)
#Test with one image only
    
print(np.shape(activations))
feature_maps = activations[0][0]
print(np.shape(feature_maps))

print(feature_maps.shape)

fig=plt.figure(figsize=(16,16))
plt.imshow(feature_maps[:,:,filter_num],cmap='gray')
plt.savefig("featuremaps-layer-{}".format(layer_num)+"-filternum-{}".format(filter_num)+'.jpg')


# Visualizing intermediate layers outputs, all filters
fig=plt.figure(figsize=(16,16))
plt.imshow(feature_maps[:,:,filter_num],cmap='gray')
plt.savefig("featuremaps-layer-{}".format(layer_num)+"-filternum-{}".format(filter_num)+'.jpg')

num_of_featuremaps=feature_maps.shape[2]
fig=plt.figure(figsize=(16,16))
plt.title("featuremaps-layer-{}".format(layer_num))
subplot_num=int(np.ceil(np.sqrt(num_of_featuremaps)))
for i in range(int(num_of_featuremaps)):
    ax= fig.add_subplot(subplot_num, subplot_num, i+1)
    ax.imshow(feature_maps[:,:,i], cmap='gray')
    plt.xticks([])
    plt.yticks([])
    plt.tight_layou()
plt.show()
fig.savefig("featuremaps-layer-{}".format(layer_num)+'.jpg')


## Other Plots

In [ ]:
print(history.history.keys())

# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

## Prediction

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

Y_pred = model.predict(X_test)
print(Y_pred)
y_pred = np.argmax(Y_pred, axis=1)
print(y_pred)
  

y_pred = model.predict_classes(X_test)
print(y_pred)

p=model.predict_proba(X_test) # to predict probability

target_names = ['class 0(EOSINOPHIL)', 'class 1(LYPHOCYTE)', 'class 2(MONOCYTE)', 'class 3(NEUTROPHIL)'] ##REVIEW
print(classification_report(np.argmax(Y_test,axis=1), y_pred,target_names=target_names))
print(confusion_matrix(np.argmax(Y_test,axis=1), y_pred))

## Test

In [ ]:
score = model.evaluate(X_test, y_test) #show_accuracy=True, verbose=0
print('Test score:', score[0])
print('Test accuracy:', score[1])
print(model.predict_classes(X_test[1:5]))
print(y_test[1:5])

In [ ]:
# visualizing intermediate layers
output_layer = model.layers[1].get_output()
output_fn = theano.function([model.layers[0].get_input()], output_layer)

In [ ]:
y_pred = model.predict(X_test)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Predicted:', decode_predictions(y_pred, top=1)[0]) #top=3

In [ ]:
#Alternative y_pred
y_pred = model.predict(X_test, batch_size=None, verbose=0, steps=None)

In [ ]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=2)

# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, 
                      classes=classes, ###
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, 
                      classes=classes, ####
                      normalize=True,
                      title='Normalized confusion matrix')

plt.show()


In [ ]:
# from sklearn.metrics import confusion_matrix

#confusion_matrix(y_train, y_test)

def pretty_confusion_matrix(y_train, y_test, labels=["False", "True"]):
    cm = confusion_matrix(y_train, y_test)
    pred_labels = ['Predicted '+ l for l in labels]
    df = pd.DataFrame(cm, index=labels, columns=pred_labels)
    return df

pretty_confusion_matrix(y_train, y_test, ['mono', 'poly'])

from sklearn.metrics import precision_score, recall_score, f1_score


print("Precision:\t{:0.3f}".format(precision_score(y, y_class_pred)))
print("Recall:  \t{:0.3f}".format(recall_score(y, y_class_pred)))
print("F1 Score:\t{:0.3f}".format(f1_score(y, y_class_pred)))

from sklearn.metrics import classification_report

print(classification_report(y, y_class_pred))